# vim: ft=yaml sw=2 ts=2 sts=2 et
engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - 'src/main/java/**.java'
    - '**.md'
exclude_paths:
  - db/
  - UML/
  - original/
