# vim: ft=yaml sw=2 ts=2 sts=2
sudo: false
language: java
jdk:
- oraclejdk8
#- openjdk8  # Not yet supported: https://docs.travis-ci.com/user/languages/java
git:
  depth: 1
branches:
  except:
  - authorization  # TODO: Remove once stable
cache:
  timeout: 60
  directories:
  - "$HOME/.m2"

install: true
script: 'mvn package -B'
deploy:
  provider: releases
  api_key:
    secure: q3oUtv41M/p3V3Q7vcLhDU2Hox/BO6wiuV9IBvR1Hzvc09VGeLnP/j3P+d9zIJOxKBUijeABX56rB3gkdgv/Afrg33CW51Bjf5hgCRXyRSVWQhHBgj5YXNcQfiT95ErfSXn73DoauMRejdyk/fHQ0IpAYddpzTceneFrAEIl9M/93GDTHnLhUedLjx+htp4sx9i3xq3XVBNy6ow40wxaDBXIRkasiyGK/1lhStf2qn60hmhIY/w7KdytiZzmNvDIgxaTr0qA2lzuvnMwT+SnGErqYaSG5kJbJBAiJbgRYuDXtTzheUlXVnh75I3Gz1y+Bnpnul0OrK7CoP059zta1/cvKpIVKCa9s+QZVCqpulygHV9iaiYda7POrO/F5FbAsk5rnsj0tMaY100lbHajKJK6z+ClpqYkmCcIlvr4/GTiqgO/YCU0R3vHXEteBDXLseN+iSgFmnDx5qJHUvtGS9aS5U1n3PxWnWVx/hGXMB8n9xSW17FXk02uf3a4GZeG7/USB9JqkIhz/D+TUBUY/in0bM+ed7DrdCuXEmbeZ5bLRyPy+pf9QbJWob7N6BgCBDfYWXUDoUFelT0GTVZAbM1lMiW+bt1ka6NmPkTOp4e/c6155/9VKGBOms2kpX48AQcfEPy4OL4V/Uea/R6S7M4D/Exu0ORi64lMbn2EDrk=
  file: package/Spring2016-proj4.jar
  skip_cleanup: true
  on:
    repo: massbay-cs/cs225-proj4
    tags: true
    jdk: oraclejdk8
    
